### ISSUE TITLE
Editor render hashes on .vtt file after edit the captions file and save

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/opencast-editor#1032]
We are under OC 13.2 and after editing the subtitles (for example add a segment on start and correct another one) I noticed that the saved .vtt having a strange hash appended

```
WEBVTT

cdsMIWME-BFRIXEgTP-r_
00:00.000 --> 00:08.500
*Musik*

C95hsdKF_mwLoqy7b86R6
00:08.500 --> 00:13.600
So, hallo, jetzt noch die zweite Session zu Vaskulitiden. 

seXSsLVMImzS1lpi5Lfzu
00:13.600 --> 00:20.920
Ich möchte Ihnen nur nochmal ganz kurz die klinischen unterschiedlichen Präsentationen noch mal zeigen,

SDneUjBi2LSE8psNDJ74e
00:20.920 --> 00:28.320
dass Sie nochmal dran erinnern hier bei der ersten Präsentation. Ich hoffe, Sie schauen die auch in der Reihenfolge
```
I tried it on editor.opencast.org but this is not occurred there. I tried to test it against stable.opencast.org but unfortunately the CC menu is not activated on editor's cfg in stable. A good idea would be to be enabled by default.

The players can load the file but still the files are not formatted according to w3c standards. Is this a bug already fixed or did I miss-configure smth?

**Comment by Arnei** [comment]
This does not occur on editor.opencast.org because a fix was recently merged: https://github.com/opencast/opencast-editor/commit/cc7d597b1b492bd2ecf5a5941e2301fe7ddb3363. It is not in a release yet. You did not misconfigure anything.

Subtitle Editing was enabled on develop.opencast.org at least at some point, seems to be disabled now. Probably best to contact whoever maintains those (Lars / lkiesow?).

Also the "strange hashes" are technically [WebVTT ids](https://www.w3.org/TR/webvtt1/#webvtt-cue-identifier) and afaik valid WebVTT.
