### ISSUE TITLE
Irregular Checkbox Behavior

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#264]
Checkboxes in the metadata tab look and behave weird. They jump, additional check marks appear at the right border and the check mark in the box is too small. This was recorded in Firefox but Chrome shows the same problem:

https://user-images.githubusercontent.com/1008395/115455517-572bad00-a222-11eb-96ca-232b12fd01c8.mp4

**Comment by Arnei** [comment]
Jumping and additional check mark appearance will be fixed by #435.

Based on my tests, the check mark in the box is not too small anymore.
![Bildschirmfoto vom 2021-09-22 11-40-30](https://user-images.githubusercontent.com/14070005/134320774-c10ff3cb-ddea-4b6e-81d4-6f7b1caf8c12.png)

So we can close this issue if #435 gets merged.

**Comment by Arnei** [comment]
#435 got merge, closing.
