### ISSUE TITLE
Unify page titles [no title vs. existing title]

### ISSUE THREAD

**Issue by cgruber-uos** [opencast/opencast-editor#898]
By clicking through the OC Studio menu you are getting this titles above the content:

| menu item | title |
|---|---|
| Schneiden | [Video title] | 
| Metadaten | "Video Metadaten" omit? or change to "Metadaten bearbeiten"? | 
| Spuren | [no title] | 
| Untertitel | [no title] | 
| Vorschaubild | "Vorschaubildeditor" omit? or change to "Vorschaubild wählen"? |
| Fertigstellen | [no title] | 

We could **omit the title** in case there is one or chang to wording in a more "call to an action" way.

**Comment by Arnei** [comment]
Omitting titles in favour of "call to actions" seems like a good idea. Although we are inconsistent about that as well. Some pages don't have one at all, and e.g. Tracks ("Spuren") has it at the bottom of the page.

Also, "Video Metadata" is technically not the page title, but the metadata catalog title, since the editor allows for editing all metadata catalogs in case you configured your events to have multiple. But we could probably omit the metadata catalog title if there is just one catalog.
